services:
  postgres:
    image: postgres:16
    container_name: finnpipe_postgres
    restart: unless-stopped
    networks:
      finnpipe_net:
        ipv4_address: 172.28.0.10
    environment:
      POSTGRES_USER: finnpipe
      POSTGRES_PASSWORD: 2437824378
      POSTGRES_DB: finnpipe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: finnpipe_clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: finnpipe
      CLICKHOUSE_PASSWORD: 2437824378
    networks:
      finnpipe_net:
        ipv4_address: 172.28.0.11
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  finnpipe_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgres_data:
  clickhouse_data: